### ISSUE TITLE
Add REFACTOR type to the list of types and the quick reference

### ISSUE THREAD

**Issue by FunkMonkey** [bluejava/git-commit-guide#1]
`REFACTOR` is mentioned in the text, but is not in the list of types. Guess it should be added.

Thanks a lot. Great and comprehensible guide!

**Comment by bluejava** [comment]
Oh, good catch, thanks! I'll fix that right now. I originally had left it in (it was in the list of types from the Angular version) but after consideration, I decided it wasn't necessary (obviously a personal subjective choice). I decided that my refactoring was almost always part of a fix or (more often) a feature, so would get very little use (and doesn't add much value to do FEAT/REFACTOR over just FEAT).  Cheers!

**Comment by FunkMonkey** [comment]
I do find `REFACTOR` quite useful actually. Probably because I often refactor without fixing bugs or adding features. And those commits don't really fit `FORMAT` as they aren't compiled-code neutral. 

Anyway. It's consistent now, that's what counts. Thanks.

**Comment by bluejava** [comment]
I certainly do think its smart for each developer/team to consider the types and decide what makes sense for their style/context. Indeed it sounds like REFACTOR is something that adds value to your commits. I agree that FORMAT doesn't work - as the idea is that FORMAT commits need not be scrutinized (as much?) when investigating bug introductions, etc. Thanks much for bringing this up!
